name: Pre-Commit
on: [push]
jobs:
  Run-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pre-commit install
      - run: pre-commit run --all-files
